# Generated by Django 5.0.7 on 2024-08-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_testament_chapter_book_testament_verse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
